databases:
  - name: studdy-buddy
    databaseName: studdy-buddy
    user: studdy-buddy

services:
  - type: web
    name: studdy-buddy
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn studdy-buddy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studdy-buddy
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4