databases:
  - name: studdybuddy
    databaseName: studdybuddy
    user: studdybuddy

services:
  - type: web
    name: studdybuddy
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn studdybuddy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studdybuddy
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4